modLoader="javafml"
loaderVersion="[43,)"
license="MIT License"

[[mods]]
modId="letmorefishlove"
version="${file.jarVersion}" #mandatory
displayName="Let More Fish Love" #mandatory
credits="" #optional
logoFile = "letfishlove_icon.png"
authors="Uraneptus" #optional
description='''
'''
[[dependencies.letmorefishlove]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.letmorefishlove]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.letmorefishlove]]
    modId="letfishlove"
    mandatory=true
    versionRange="[1.0.3,)"
    ordering="NONE"
    side="BOTH"